"""Scribe API - Mac screen transcription with speaker learning."""

import logging
import os
import secrets
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, Request, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from .models.database import init_db
from .routers import recordings_router, speakers_router, segments_router

# API Security: Shared secret token
# Per SPEC.md Section 6.1 & 8.1: API requires Authorization: Bearer <shared_secret>
# In production, this token is generated by Tauri on startup and passed to the sidecar
API_SECRET_TOKEN: Optional[str] = os.getenv("SCRIBE_API_SECRET")

# If no secret is provided, generate one and print it (for standalone development)
if not API_SECRET_TOKEN and os.getenv("SCRIBE_REQUIRE_AUTH", "false").lower() == "true":
    API_SECRET_TOKEN = secrets.token_urlsafe(32)
    print(f"Generated API secret token: {API_SECRET_TOKEN}")


class AuthMiddleware(BaseHTTPMiddleware):
    """
    Middleware to enforce shared secret token authentication.

    Per SPEC.md Section 8.1:
    - Require shared secret token in Authorization header
    - Token generated by Tauri on each app startup
    - Reject all requests without valid token
    """

    EXEMPT_PATHS = {"/", "/health", "/docs", "/redoc", "/openapi.json"}

    async def dispatch(self, request: Request, call_next):
        # Skip auth check if no secret is configured (development mode)
        if not API_SECRET_TOKEN:
            return await call_next(request)

        # Skip auth for exempt paths (health check, docs)
        if request.url.path in self.EXEMPT_PATHS:
            return await call_next(request)

        # Check Authorization header
        auth_header = request.headers.get("Authorization")
        if not auth_header:
            return JSONResponse(
                status_code=401,
                content={"detail": "Missing Authorization header"},
            )

        # Validate Bearer token
        if not auth_header.startswith("Bearer "):
            return JSONResponse(
                status_code=401,
                content={"detail": "Invalid Authorization header format"},
            )

        token = auth_header[7:]  # Remove "Bearer " prefix
        if not secrets.compare_digest(token, API_SECRET_TOKEN):
            return JSONResponse(
                status_code=403,
                content={"detail": "Invalid API token"},
            )

        return await call_next(request)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifespan handler."""
    # Startup
    logger.info("Initializing Scribe API...")

    # Initialize database
    await init_db()
    logger.info("Database initialized")

    # Create upload directory
    os.makedirs("data/uploads", exist_ok=True)
    os.makedirs("models", exist_ok=True)

    yield

    # Shutdown
    logger.info("Shutting down Scribe API...")


app = FastAPI(
    title="Scribe API",
    description="Mac screen transcription with speaker learning",
    version="1.0.0",
    lifespan=lifespan,
)

# Security middleware (must be added before CORS)
# Per SPEC.md Section 8.1: Require shared secret token
app.add_middleware(AuthMiddleware)

# CORS middleware - only allow localhost origins for security
# Per SPEC.md: API binds to 127.0.0.1 only
ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "tauri://localhost",  # Tauri WebView
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(recordings_router, prefix="/api/v1")
app.include_router(speakers_router, prefix="/api/v1")
app.include_router(segments_router, prefix="/api/v1")


@app.get("/")
async def root():
    """Root endpoint."""
    return {
        "name": "Scribe API",
        "version": "1.0.0",
        "docs": "/docs",
    }


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy"}


@app.exception_handler(Exception)
async def global_exception_handler(request, exc):
    """Global exception handler."""
    logger.error(f"Unhandled exception: {exc}", exc_info=True)
    return JSONResponse(
        status_code=500,
        content={"detail": "Internal server error"},
    )


# Run with: uvicorn scribe_api.main:app --reload --port 5005
if __name__ == "__main__":
    import uvicorn

    # Per SPEC.md Section 8.1: Bind STRICTLY to 127.0.0.1 (no 0.0.0.0)
    # This ensures the API is only accessible from localhost
    uvicorn.run(
        "scribe_api.main:app",
        host="127.0.0.1",  # Security: localhost only
        port=int(os.getenv("PORT", "5005")),
        reload=os.getenv("DEBUG", "false").lower() == "true",
    )
